# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapCanvasTest
                                 A QGIS plugin
 Map Canvas Test
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-04-22
        copyright            : (C) 2019 by Eric Brelsford
        email                : ebrelsford@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapCanvasTest class from file MapCanvasTest.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .map_canvas_test import MapCanvasTest
    return MapCanvasTest(iface)
